// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaInB2cZyJpd8clIZjlXiiAdVLyIkgvRQ',
    appId: '1:469870852908:web:6c48f108cdd4cd26274a89',
    messagingSenderId: '469870852908',
    projectId: 'firstprjct-5cc19',
    authDomain: 'firstprjct-5cc19.firebaseapp.com',
    storageBucket: 'firstprjct-5cc19.appspot.com',
    measurementId: 'G-PFZZJ4CTSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaVhW0UyR1rgX-PviFolcogW-CEjd5Cl8',
    appId: '1:469870852908:android:3b9f294f1e996f29274a89',
    messagingSenderId: '469870852908',
    projectId: 'firstprjct-5cc19',
    storageBucket: 'firstprjct-5cc19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArDG1YbewC_tKsYK9m8MAYUGvk0wG9XwE',
    appId: '1:469870852908:ios:4000886f6f2ed138274a89',
    messagingSenderId: '469870852908',
    projectId: 'firstprjct-5cc19',
    storageBucket: 'firstprjct-5cc19.appspot.com',
    iosBundleId: 'com.example.signUp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArDG1YbewC_tKsYK9m8MAYUGvk0wG9XwE',
    appId: '1:469870852908:ios:4000886f6f2ed138274a89',
    messagingSenderId: '469870852908',
    projectId: 'firstprjct-5cc19',
    storageBucket: 'firstprjct-5cc19.appspot.com',
    iosBundleId: 'com.example.signUp',
  );
}
